baseURL = "https://labs.debruyn.dev/"
languageCode = "en-us"
title = "Data Engineer 101"
theme = "hugo-cards"

[params]
  description = "A list of useful websites and tools for (aspiring) data engineers"
  repo = "https://github.com/sdebruyn/data-engineer-101"
  analytics = "UA-51718684-3"
